title: <p align = "center"> Daryle Bilog </p>

logo: "/images/daryle_profile.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/daryle-bilog/">LinkedIn</a> |
  <a href="/BILOG_DARYLE_RESUME_08_Aug_24.pdf">Resume</a> |
  <a href="https://github.com/darylebilog">GitHub</a>
  </p>

  <p align = "justify">
  ğŸ“ I hold a Master of Science in Business Analytics from the Davis Eccles School of Business at the University of Utah, and I began my journey with a Business Management degree focused on Marketing at Brigham Young University - Hawaii.
  <br><br>
  ğŸ’» Iâ€™m passionate about using SQL, R, and Python for data analysis to uncover trends and drive decisions, and I create engaging dashboards in Tableau, Looker Studio, and Marketing Cloud Intelligence.
  <br><br>
  ğŸŒ Outside of data, I enjoy singing and hiking in nature, and I believe in lifelong learning and the joy of discovering something new!
  </p>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
