title: <p align = "center"> Daryle Bilog </p>

logo: <div style="text-align: center;">
      <img src="/images/daryle_profile.png?raw=true" alt="Daryle Bilog" style="max-width: 150px; height: auto;">
      </div>

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/daryle-bilog/">LinkedIn</a> |
  <a href="/BILOG_DARYLE_RESUME_08_Aug_24.pdf">Resume</a> |
  <a href="https://github.com/darylebilog">GitHub</a>
  </p>

  <p align = "justify">
  ğŸ“ Iâ€™m a proud graduate with a Master of Science in Business Analytics from the fantastic Davis Eccles School of Business at the University of Utah! My journey started with an undergraduate degree in Business Managementâ€”where I focused on Marketing and dabbled in Information Systems, Math, and even Theaterâ€”at Brigham Young University - Hawaii.
  <br><br>
  ğŸ’» Iâ€™m all about the numbers and insights! With a toolkit that includes SQL, R, and Python, I thrive on analyzing data to uncover trends and drive decision-making. I love crafting eye-catching dashboards in Tableau, Looker Studio, and Marketing Cloud Intelligence. Collaboration is my jam, and I thrive on working with others to turn data into actionable magic.
  <br><br>
  ğŸŒ When I am not diving into data, you can find me belting out my favorite tunes or hitting the trails to explore the breathtaking wonders of nature. I believe in lifelong learningâ€”there is always something new to discover, and I am here for it!
  </p>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
