title: <p align = "center"> Daryle Bilog </p>

logo: /images/daryle_profile.png?raw=true" alt="Daryle Bilog" style="max-width: 150px; height: auto;">

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/daryle-bilog/">LinkedIn</a> |
  <a href="/BILOG_DARYLE_RESUME_08_Aug_24.pdf">Resume</a> |
  <a href="https://github.com/darylebilog">GitHub</a>
  </p>

  <p align = "justify">
  ğŸ“ I hold a Master of Science in Business Analytics from the Davis Eccles School of Business at the University of Utah, and I earned my undergraduate degree in Business Management with a focus on Marketing at Brigham Young University - Hawaii.
  <br><br>
  ğŸ’» I specialize in data analysis using SQL, R, and Python to uncover trends and drive decision-making. I enjoy creating engaging dashboards in Tableau, Looker Studio, and Marketing Cloud Intelligence, and I thrive on collaboration to turn data into actionable insights.
  <br><br>
  ğŸŒ When Iâ€™m not immersed in data, you can find me singing my heart out or exploring the great outdoors. Iâ€™m a lifelong learner, always eager to discover something new!
  </p>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
